import type { Client, Transaction } from "@/lib/types";

export const demoTransactions: Transaction[] = [
  {
    id: "demo-1",
    user_id: "demo",
    business_id: null,
    client_id: null,
    document_id: null,
    supplier_name: "Bunnings Warehouse",
    supplier_abn: "26 008 672 179",
    invoice_number: "BW-10482",
    invoice_date: "2026-05-28",
    due_date: "2026-06-12",
    description: "Tools and site supplies",
    category: "Equipment and tools",
    subtotal: 245.45,
    gst_amount: 24.55,
    total_amount: 270,
    currency: "AUD",
    confidence_score: 97,
    status: "extracted",
    notes: "Ready for approval",
    created_at: "2026-05-28T08:12:00Z",
    updated_at: "2026-05-28T08:12:00Z",
  },
  {
    id: "demo-2",
    user_id: "demo",
    business_id: null,
    client_id: null,
    document_id: null,
    supplier_name: "Ampol",
    supplier_abn: "40 004 201 307",
    invoice_number: "R-78211",
    invoice_date: "2026-05-30",
    due_date: "",
    description: "Fuel receipt",
    category: "Fuel and motor vehicle",
    subtotal: 86.82,
    gst_amount: 8.68,
    total_amount: 95.5,
    currency: "AUD",
    confidence_score: 89,
    status: "needs_review",
    notes: "Check receipt date",
    created_at: "2026-05-30T10:35:00Z",
    updated_at: "2026-05-30T10:35:00Z",
  },
];

export const demoClients: Client[] = [
  {
    id: "client-1",
    business_name: "Harbour Electrical Co",
    contact_name: "Sam Harper",
    email: "sam@example.com",
    abn: "53 004 085 616",
    status: "Active",
  },
  {
    id: "client-2",
    business_name: "Northside Plumbing",
    contact_name: "Tara Nguyen",
    email: "tara@example.com",
    abn: "11 223 344 556",
    status: "Awaiting documents",
  },
];
