import type { Customer, FollowUpCase, FollowUpMessage } from "@/lib/types";

export const demoCustomers: Customer[] = [
  {
    id: "customer-1",
    company_name: "Harbour Electrical Co",
    contact_name: "Sam Harper",
    email: "sam@example.com",
    phone: "+61 400 100 200",
    lifecycle_stage: "quoted",
    total_revenue_at_risk: 4850,
    last_contacted_at: "2026-05-29T04:00:00Z",
    notes: "Asked for a start date after receiving the quote.",
  },
  {
    id: "customer-2",
    company_name: "Northside Plumbing",
    contact_name: "Tara Nguyen",
    email: "tara@example.com",
    phone: "+61 411 222 333",
    lifecycle_stage: "customer",
    total_revenue_at_risk: 1260,
    last_contacted_at: "2026-05-27T02:15:00Z",
    notes: "Usually pays after SMS reminder.",
  },
  {
    id: "customer-3",
    company_name: "Bright Dental Studio",
    contact_name: "Mina Patel",
    email: "mina@example.com",
    phone: "+61 422 444 555",
    lifecycle_stage: "lead",
    total_revenue_at_risk: 3200,
    last_contacted_at: null,
    notes: "Website enquiry for recurring cleaning package.",
  },
];

export const demoFollowUpCases: FollowUpCase[] = [
  {
    id: "demo-1",
    customer_id: "customer-1",
    customer: demoCustomers[0],
    case_type: "quote",
    title: "Commercial fit-out quote #Q-2044",
    source: "hubspot",
    amount_cents: 485000,
    currency: "AUD",
    due_date: "2026-05-30",
    last_contacted_at: "2026-05-29T04:00:00Z",
    next_follow_up_at: "2026-06-01T23:00:00Z",
    recovery_score: 88,
    status: "drafted",
    channel: "email",
    draft_subject: "Quick follow-up on your fit-out quote",
    draft_body:
      "Hi Sam, just checking whether you had any questions about quote Q-2044. We can still hold the proposed start window if you would like to go ahead this week.",
    sequence_name: "Quote win-back",
    notes: "High value quote, no reply for 72 hours.",
    created_at: "2026-05-29T04:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "demo-2",
    customer_id: "customer-2",
    customer: demoCustomers[1],
    case_type: "invoice",
    title: "Invoice INV-1187",
    source: "quickbooks",
    amount_cents: 126000,
    currency: "AUD",
    due_date: "2026-05-24",
    last_contacted_at: "2026-05-27T02:15:00Z",
    next_follow_up_at: "2026-06-01T22:00:00Z",
    recovery_score: 76,
    status: "scheduled",
    channel: "sms",
    draft_subject: null,
    draft_body:
      "Hi Tara, a quick reminder that invoice INV-1187 for $1,260 is still open. You can reply here if anything looks off.",
    sequence_name: "Invoice recovery",
    notes: "Second reminder should stay friendly.",
    created_at: "2026-05-24T00:00:00Z",
    updated_at: "2026-06-01T00:10:00Z",
  },
  {
    id: "demo-3",
    customer_id: "customer-3",
    customer: demoCustomers[2],
    case_type: "lead",
    title: "Website enquiry for recurring cleaning",
    source: "calendly",
    amount_cents: 320000,
    currency: "AUD",
    due_date: null,
    last_contacted_at: null,
    next_follow_up_at: "2026-06-02T00:00:00Z",
    recovery_score: 64,
    status: "new",
    channel: "email",
    draft_subject: "Want to book your cleaning walkthrough?",
    draft_body:
      "Hi Mina, thanks for asking about recurring cleaning. Would you like to pick a time for a quick walkthrough this week?",
    sequence_name: "Lead speed-to-book",
    notes: "New lead from booking page.",
    created_at: "2026-06-01T01:10:00Z",
    updated_at: "2026-06-01T01:10:00Z",
  },
];

export const demoMessages: FollowUpMessage[] = [
  {
    id: "message-1",
    case_id: "demo-1",
    channel: "email",
    subject: "Quick follow-up on your fit-out quote",
    body: demoFollowUpCases[0].draft_body ?? "",
    status: "draft",
    provider: "gmail",
    scheduled_at: null,
    sent_at: null,
    error_message: null,
    created_at: "2026-06-01T00:00:00Z",
  },
];
