import type {
  BlockedNumber,
  Business,
  BusinessSettings,
  Contact,
  Conversation,
  Lead,
  Message,
  MissedCall,
} from "@/lib/types";

export const demoBusiness: Business = {
  id: "business-demo",
  name: "Harbour Electrical Co",
  industry: "Electrical services",
  timezone: "Australia/Sydney",
  main_phone: "+61 2 5550 0100",
  created_at: "2026-05-01T00:00:00Z",
};

export const demoSettings: BusinessSettings = {
  business_id: demoBusiness.id,
  auto_reply_enabled: true,
  reply_after_missed_call: true,
  reply_during_business_hours_only: false,
  business_hours: {
    monday: { open: "08:00", close: "17:30", enabled: true },
    tuesday: { open: "08:00", close: "17:30", enabled: true },
    wednesday: { open: "08:00", close: "17:30", enabled: true },
    thursday: { open: "08:00", close: "17:30", enabled: true },
    friday: { open: "08:00", close: "17:30", enabled: true },
    saturday: { open: "09:00", close: "13:00", enabled: true },
    sunday: { open: "00:00", close: "00:00", enabled: false },
  },
  after_hours_message:
    "Thanks for calling [Business Name]. We are currently closed, but reply here and our AI assistant will collect the details for the owner.",
  emergency_keywords: ["smoke", "fire", "flood", "burst", "sparking", "emergency", "unsafe"],
  ignored_keywords: ["wrong number", "telemarketer", "sales pitch"],
  max_ai_messages_per_conversation: 8,
  owner_notification_phone: "+61 400 111 222",
  owner_notification_email: "owner@example.com",
};

export const demoMissedCalls: MissedCall[] = [
  {
    id: "call-1",
    business_id: demoBusiness.id,
    caller_phone: "+61 411 222 333",
    caller_name: "Mia Chen",
    twilio_call_sid: "CA-demo-1",
    call_time: "2026-06-01T08:16:00Z",
    status: "converted",
    auto_reply_sent: true,
    ignored_reason: null,
    created_at: "2026-06-01T08:16:00Z",
  },
  {
    id: "call-2",
    business_id: demoBusiness.id,
    caller_phone: "+61 422 555 888",
    caller_name: null,
    twilio_call_sid: "CA-demo-2",
    call_time: "2026-06-01T07:44:00Z",
    status: "auto_replied",
    auto_reply_sent: true,
    ignored_reason: null,
    created_at: "2026-06-01T07:44:00Z",
  },
  {
    id: "call-3",
    business_id: demoBusiness.id,
    caller_phone: "+61 400 999 111",
    caller_name: "Brother",
    twilio_call_sid: "CA-demo-3",
    call_time: "2026-06-01T06:11:00Z",
    status: "ignored",
    auto_reply_sent: false,
    ignored_reason: "Saved personal contact",
    created_at: "2026-06-01T06:11:00Z",
  },
];

export const demoConversations: Conversation[] = [
  {
    id: "conversation-1",
    business_id: demoBusiness.id,
    missed_call_id: "call-1",
    caller_phone: "+61 411 222 333",
    category: "new_lead",
    status: "complete",
    ai_summary:
      "Mia needs a quote for an aircon install in Bondi. Preferred callback is today after 3pm.",
    confidence_score: 92,
    urgency: "medium",
    created_at: "2026-06-01T08:16:00Z",
    updated_at: "2026-06-01T08:22:00Z",
  },
  {
    id: "conversation-2",
    business_id: demoBusiness.id,
    missed_call_id: "call-2",
    caller_phone: "+61 422 555 888",
    category: "emergency",
    status: "escalated",
    ai_summary:
      "Caller reported a smoking switchboard. AI told them to call emergency services if unsafe and notified owner immediately.",
    confidence_score: 98,
    urgency: "emergency",
    created_at: "2026-06-01T07:44:00Z",
    updated_at: "2026-06-01T07:46:00Z",
  },
  {
    id: "conversation-3",
    business_id: demoBusiness.id,
    missed_call_id: "call-3",
    caller_phone: "+61 400 999 111",
    category: "personal",
    status: "stopped",
    ai_summary: "Personal family call. No lead created.",
    confidence_score: 96,
    urgency: "low",
    created_at: "2026-06-01T06:11:00Z",
    updated_at: "2026-06-01T06:12:00Z",
  },
];

export const demoMessages: Message[] = [
  {
    id: "message-1",
    conversation_id: "conversation-1",
    sender_type: "ai",
    sender_phone: demoBusiness.main_phone,
    body: "Hi, thanks for calling Harbour Electrical Co. Sorry we missed your call. What can we help with?",
    twilio_message_sid: "SM-demo-1",
    direction: "outbound",
    created_at: "2026-06-01T08:16:08Z",
  },
  {
    id: "message-2",
    conversation_id: "conversation-1",
    sender_type: "caller",
    sender_phone: "+61 411 222 333",
    body: "Need a quote for aircon install in Bondi.",
    twilio_message_sid: "SM-demo-2",
    direction: "inbound",
    created_at: "2026-06-01T08:17:00Z",
  },
  {
    id: "message-3",
    conversation_id: "conversation-1",
    sender_type: "ai",
    sender_phone: demoBusiness.main_phone,
    body: "Thanks. What is your name and what time would be best for the owner to call you back?",
    twilio_message_sid: "SM-demo-3",
    direction: "outbound",
    created_at: "2026-06-01T08:17:05Z",
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead-1",
    business_id: demoBusiness.id,
    conversation_id: "conversation-1",
    name: "Mia Chen",
    phone: "+61 411 222 333",
    enquiry_type: "Aircon install quote",
    job_description: "Install a split-system aircon at a Bondi apartment.",
    urgency: "medium",
    address: "Bondi NSW",
    preferred_callback_time: "Today after 3pm",
    status: "new",
    estimated_value: 2400,
    notes: "Captured from missed call SMS conversation.",
    created_at: "2026-06-01T08:22:00Z",
    updated_at: "2026-06-01T08:22:00Z",
  },
  {
    id: "lead-2",
    business_id: demoBusiness.id,
    conversation_id: "conversation-2",
    name: "Unknown caller",
    phone: "+61 422 555 888",
    enquiry_type: "Electrical emergency",
    job_description: "Switchboard is smoking.",
    urgency: "emergency",
    address: "",
    preferred_callback_time: "Immediate",
    status: "emergency",
    estimated_value: null,
    notes: "Owner notified immediately.",
    created_at: "2026-06-01T07:46:00Z",
    updated_at: "2026-06-01T07:46:00Z",
  },
];

export const demoContacts: Contact[] = [
  {
    id: "contact-1",
    business_id: demoBusiness.id,
    name: "Alex Harper",
    phone: "+61 400 999 111",
    contact_type: "family",
    notes: "Owner's brother. Do not AI qualify.",
    auto_reply_allowed: false,
  },
  {
    id: "contact-2",
    business_id: demoBusiness.id,
    name: "Tara Nguyen",
    phone: "+61 411 777 888",
    contact_type: "customer",
    notes: "Existing maintenance customer.",
    auto_reply_allowed: true,
  },
];

export const demoBlockedNumbers: BlockedNumber[] = [
  {
    id: "blocked-1",
    business_id: demoBusiness.id,
    phone: "+61 2 9999 0000",
    reason: "Repeated spam calls",
    created_at: "2026-05-24T00:00:00Z",
  },
];
